In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("mvc.csv", low_memory=False)
df

,CRASH DATE,CRASH TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
0,01/11/2020,10:30,NaN,NaN,NaN,NaN,NaN,ALEXANDER HAMILTON BRIDGE,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4272183,Pick-up Truck,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
1,12/31/2019,12:00,QUEENS,11368,40.738950,-73.852720,"(40.73895, -73.85272)",NaN,NaN,59-30 108 STREET,...,Unspecified,NaN,NaN,NaN,4267173,Sedan,Sedan,NaN,NaN,NaN
2,01/12/2020,19:40,NaN,NaN,40.763020,-73.770690,"(40.76302, -73.77069)",BELL BOULEVARD,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4272143,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
3,01/13/2020,11:50,QUEENS,11355,40.754818,-73.828070,"(40.754818, -73.82807)",NaN,NaN,42-28 MAIN STREET,...,Unspecified,NaN,NaN,NaN,4272869,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
4,12/17/2019,17:20,BRONX,10475,40.886845,-73.825230,"(40.886845, -73.82523)",BOSTON ROAD,HEATHCOTE AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4261087,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1722529,07/06/2012,18:00,QUEENS,11377,40.746146,-73.898108,"(40.7461455, -73.8981085)",ROOSEVELT AVENUE,67 STREET,NaN,...,Unspecified,NaN,NaN,NaN,238690,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
1722530,07/04/2012,16:38,QUEENS,11385,40.700652,-73.896270,"(40.7006522, -73.8962702)",MYRTLE AVENUE,60 LANE,NaN,...,Unspecified,NaN,NaN,NaN,213225,PASSENGER VEHICLE,PICK-UP TRUCK,NaN,NaN,NaN
1722531,07/11/2012,16:10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Unspecified,NaN,NaN,NaN,2896749,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,NaN,NaN,NaN
1722532,07/08/2012,2:45,BROOKLYN,11208,40.667955,-73.870064,"(40.6679546, -73.8700642)",LINDEN BOULEVARD,EUCLID AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,163455,SPORT UTILITY / STATION WAGON,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
1722533,07/02/2012,20:34,QUEENS,11426,40.733213,-73.717604,"(40.733213, -73.7176035)",249 STREET,85 AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,219412,PASSENGER VEHICLE,UNKNOWN,NaN,NaN,NaN

In [4]:
factors=df[["CONTRIBUTING FACTOR VEHICLE 1","CONTRIBUTING FACTOR VEHICLE 2","CONTRIBUTING FACTOR VEHICLE 3","CONTRIBUTING FACTOR VEHICLE 4","CONTRIBUTING FACTOR VEHICLE 5","NUMBER OF PERSONS INJURED","NUMBER OF PERSONS KILLED"]]
factors.loc[(factors["CONTRIBUTING FACTOR VEHICLE 1"]=="Unspecified")&((factors["CONTRIBUTING FACTOR VEHICLE 2"]!="Unspecified")&(factors["CONTRIBUTING FACTOR VEHICLE 2"].notna()))]

Empty DataFrame
Columns: [CONTRIBUTING FACTOR VEHICLE 1, CONTRIBUTING FACTOR VEHICLE 2, CONTRIBUTING FACTOR VEHICLE 3, CONTRIBUTING FACTOR VEHICLE 4, CONTRIBUTING FACTOR VEHICLE 5, NUMBER OF PERSONS INJURED, NUMBER OF PERSONS KILLED]
Index: []

In [5]:
factors=factors.loc[(factors["CONTRIBUTING FACTOR VEHICLE 1"]!="Unspecified")]
factors

,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED
1,Following Too Closely,Unspecified,NaN,NaN,NaN,1.0,0.0
2,Driver Inattention/Distraction,Unspecified,NaN,NaN,NaN,0.0,0.0
3,Backing Unsafely,Unspecified,NaN,NaN,NaN,0.0,0.0
4,Driver Inattention/Distraction,Unspecified,NaN,NaN,NaN,0.0,0.0
5,Failure to Yield Right-of-Way,NaN,NaN,NaN,NaN,1.0,0.0
...,...,...,...,...,...,...,...
1722525,Fatigued/Drowsy,Fatigued/Drowsy,NaN,NaN,NaN,0.0,0.0
1722526,Driver Inattention/Distraction,Unspecified,NaN,NaN,NaN,2.0,0.0
1722529,Fatigued/Drowsy,Unspecified,NaN,NaN,NaN,0.0,0.0
1722531,Fatigued/Drowsy,Unspecified,NaN,NaN,NaN,1.0,0.0
1722533,Driver Inexperience,Unspecified,NaN,NaN,NaN,0.0,0.0

In [6]:
factors=factors.loc[factors["CONTRIBUTING FACTOR VEHICLE 1"].notna()].reset_index(drop=True)
factors

,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED
0,Following Too Closely,Unspecified,NaN,NaN,NaN,1.0,0.0
1,Driver Inattention/Distraction,Unspecified,NaN,NaN,NaN,0.0,0.0
2,Backing Unsafely,Unspecified,NaN,NaN,NaN,0.0,0.0
3,Driver Inattention/Distraction,Unspecified,NaN,NaN,NaN,0.0,0.0
4,Failure to Yield Right-of-Way,NaN,NaN,NaN,NaN,1.0,0.0
...,...,...,...,...,...,...,...
1097485,Fatigued/Drowsy,Fatigued/Drowsy,NaN,NaN,NaN,0.0,0.0
1097486,Driver Inattention/Distraction,Unspecified,NaN,NaN,NaN,2.0,0.0
1097487,Fatigued/Drowsy,Unspecified,NaN,NaN,NaN,0.0,0.0
1097488,Fatigued/Drowsy,Unspecified,NaN,NaN,NaN,1.0,0.0
1097489,Driver Inexperience,Unspecified,NaN,NaN,NaN,0.0,0.0

In [7]:
factors.head(100)

,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED
0,Following Too Closely,Unspecified,NaN,NaN,NaN,1.0,0.0
1,Driver Inattention/Distraction,Unspecified,NaN,NaN,NaN,0.0,0.0
2,Backing Unsafely,Unspecified,NaN,NaN,NaN,0.0,0.0
3,Driver Inattention/Distraction,Unspecified,NaN,NaN,NaN,0.0,0.0
4,Failure to Yield Right-of-Way,NaN,NaN,NaN,NaN,1.0,0.0
...,...,...,...,...,...,...,...
95,Following Too Closely,Unspecified,NaN,NaN,NaN,0.0,0.0
96,Driver Inattention/Distraction,Unspecified,NaN,NaN,NaN,0.0,0.0
97,Reaction to Uninvolved Vehicle,Unspecified,NaN,NaN,NaN,0.0,0.0
98,Fatigued/Drowsy,Unspecified,NaN,NaN,NaN,0.0,0.0
99,Driver Inattention/Distraction,NaN,NaN,NaN,NaN,0.0,0.0

In [14]:
arr=["Unspecified","Other Vehicular","1","80"]
factors=factors.replace(arr,np.NaN)

In [15]:
factors.loc[factors["CONTRIBUTING FACTOR VEHICLE 1"]=="80"]

Empty DataFrame
Columns: [CONTRIBUTING FACTOR VEHICLE 1, CONTRIBUTING FACTOR VEHICLE 2, CONTRIBUTING FACTOR VEHICLE 3, CONTRIBUTING FACTOR VEHICLE 4, CONTRIBUTING FACTOR VEHICLE 5, NUMBER OF PERSONS INJURED, NUMBER OF PERSONS KILLED]
Index: []

In [18]:
factors=factors.rename(columns={"CONTRIBUTING FACTOR VEHICLE 1":"F1","CONTRIBUTING FACTOR VEHICLE 2":"F2","CONTRIBUTING FACTOR VEHICLE 3":"F3","CONTRIBUTING FACTOR VEHICLE 4":"F4","CONTRIBUTING FACTOR VEHICLE 5":"F5"})
factors

,F1,F2,F3,F4,F5,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED
0,Following Too Closely,NaN,NaN,NaN,NaN,1.0,0.0
1,Driver Inattention/Distraction,NaN,NaN,NaN,NaN,0.0,0.0
2,Backing Unsafely,NaN,NaN,NaN,NaN,0.0,0.0
3,Driver Inattention/Distraction,NaN,NaN,NaN,NaN,0.0,0.0
4,Failure to Yield Right-of-Way,NaN,NaN,NaN,NaN,1.0,0.0
...,...,...,...,...,...,...,...
1097485,Fatigued/Drowsy,Fatigued/Drowsy,NaN,NaN,NaN,0.0,0.0
1097486,Driver Inattention/Distraction,NaN,NaN,NaN,NaN,2.0,0.0
1097487,Fatigued/Drowsy,NaN,NaN,NaN,NaN,0.0,0.0
1097488,Fatigued/Drowsy,NaN,NaN,NaN,NaN,1.0,0.0
1097489,Driver Inexperience,NaN,NaN,NaN,NaN,0.0,0.0

In [23]:
factors=factors.loc[(factors["F1"].notna())|(factors["F2"].notna())|(factors["F3"].notna())|(factors["F4"].notna())|(factors["F5"].notna())].reset_index(drop=True)
factors

,F1,F2,F3,F4,F5,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED
0,Following Too Closely,NaN,NaN,NaN,NaN,1.0,0.0
1,Driver Inattention/Distraction,NaN,NaN,NaN,NaN,0.0,0.0
2,Backing Unsafely,NaN,NaN,NaN,NaN,0.0,0.0
3,Driver Inattention/Distraction,NaN,NaN,NaN,NaN,0.0,0.0
4,Failure to Yield Right-of-Way,NaN,NaN,NaN,NaN,1.0,0.0
...,...,...,...,...,...,...,...
1060419,Fatigued/Drowsy,Fatigued/Drowsy,NaN,NaN,NaN,0.0,0.0
1060420,Driver Inattention/Distraction,NaN,NaN,NaN,NaN,2.0,0.0
1060421,Fatigued/Drowsy,NaN,NaN,NaN,NaN,0.0,0.0
1060422,Fatigued/Drowsy,NaN,NaN,NaN,NaN,1.0,0.0
1060423,Driver Inexperience,NaN,NaN,NaN,NaN,0.0,0.0